type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table"
      parameters:
        componentName: "Start"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
    Create Table:
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create Table"
        createMethod: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "GROC_ORDERS"
        snowflakeTableType: "Permanent"
        columns:
        - - "DATA_VALUE"
          - "VARIANT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://anuragawa/matillion/groceries_orders_flat.json"
        pattern: ".*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "GROC_ORDERS"
        loadColumns:
        - "DATA_VALUE"
        format: "[Custom]"
        fileType: "JSON"
        compression: "AUTO"
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
        enableOctal: "False"
        allowDuplicates: "False"
        stripOuterArray: "False"
        stripNullValues: "False"
        ignoreUtf8Errors: "False"
        nullIf1:
        trimSpace1: "False"
        matchByColumnName: "None"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
design:
  components:
    Start:
      position:
        x: -460
        "y": -30
      tempMetlId:
    Create Table:
      position:
        x: -330
        "y": -30
      tempMetlId:
    S3 Load:
      position:
        x: -170
        "y": -30
      tempMetlId:
