type: "transformation"
version: "1.0"
pipeline:
  components:
    Extract Nested Data:
      type: "extract-nested-data-sf"
      sources:
      - "GROC_ORDERS"
      parameters:
        componentName: "Extract Nested Data"
        includeInputColumns: "Yes"
        columns:
        - name: "-element"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "-element"
          isArray: "false"
          include: "true"
          childElements:
          - name: "item_name"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "item_name"
            isArray: "false"
            include: "true"
          - name: "customer_name"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "customer_name"
            isArray: "false"
            include: "true"
          - name: "total_price"
            datatype: "FLOAT"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "total_price"
            isArray: "false"
            include: "true"
          - name: "order_date"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "order_date"
            isArray: "false"
            include: "true"
          - name: "item_id"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "item_id"
            isArray: "false"
            include: "true"
          - name: "customer_id"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "customer_id"
            isArray: "false"
            include: "true"
          - name: "postal_code"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "postal_code"
            isArray: "false"
            include: "true"
          - name: "unit_price"
            datatype: "FLOAT"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "unit_price"
            isArray: "false"
            include: "true"
          - name: "order_id"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "order_id"
            isArray: "false"
            include: "true"
          - name: "store_name"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "store_name"
            isArray: "false"
            include: "true"
          - name: "status"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "status"
            isArray: "false"
            include: "true"
          - name: "city"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "city"
            isArray: "false"
            include: "true"
          - name: "payment_method"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "payment_method"
            isArray: "false"
            include: "true"
          - name: "delivery_date"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "delivery_date"
            isArray: "false"
            include: "true"
          - name: "quantity"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "quantity"
            isArray: "false"
            include: "true"
          - name: "store_id"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "store_id"
            isArray: "false"
            include: "true"
          - name: "state"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "state"
            isArray: "false"
            include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    GROC_ORDERS:
      type: "table-input"
      parameters:
        componentName: "GROC_ORDERS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "GROC_ORDERS"
        columnNames:
        - "DATA_VALUE"
        timeOffset:
design:
  components:
    Extract Nested Data:
      position:
        x: -430
        "y": -40
      tempMetlId:
    GROC_ORDERS:
      position:
        x: -660
        "y": -40
      tempMetlId:
