type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "SQL Script"
      parameters:
        componentName: "Start"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
    SQL Script:
      type: "sql-executor"
      transitions:
        success:
        - "Fixed Iterator"
      parameters:
        componentName: "SQL Script"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        enableVariableResolution: "No"
        sqlScript: "CREATE TABLE TRANSACTIONS_NEW IF NOT EXISTS (\r\ntrans_id INT,\t\
          \r\naccount_id\tINT,\r\nDate\tDATE,\r\nType\tVARCHAR(30),\r\noperation\t\
          VARCHAR(40),\r\namount\tINT,\r\nbalance\tFLOAT,\r\nPurpose\tVARCHAR(40),\r\
          \nbank\tVARCHAR(45),\r\naccount INT);"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://anuragawa/matillion/transaction_awa/${filename}"
        pattern: ".*\\csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "TRANSACTIONS_NEW"
        loadColumns:
        - "TRANS_ID"
        - "ACCOUNT_ID"
        - "DATE"
        - "TYPE"
        - "OPERATION"
        - "AMOUNT"
        - "BALANCE"
        - "PURPOSE"
        - "BANK"
        - "ACCOUNT"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
    Fixed Iterator:
      type: "fixed-iterator"
      iterationTarget: "S3 Load"
      parameters:
        componentName: "Fixed Iterator"
        concurrency: "Sequential"
        variablesToIterate:
        - "filename"
        iterationValues:
        - - "trnx_16.csv"
        - - "trnx_17.csv"
        - - "trnx_18.csv"
        - - "trnx_19.csv"
        - - "trnx_20.csv"
        - - "trnx_21.csv"
        breakOnFailure: "Yes"
        stopOnCondition: "No"
        recordValuesInTaskHistory: "Yes"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        updateGridVariables:
  variables:
    filename:
      metadata:
        type: "TEXT"
        description: "this variable will help usto pass the required file"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "trnx_16.csv"
design:
  components:
    Start:
      position:
        x: -500
        "y": -50
      tempMetlId:
    SQL Script:
      position:
        x: -330
        "y": -50
      tempMetlId:
    S3 Load:
      position:
        x: -180
        "y": -50
      tempMetlId:
    Fixed Iterator:
      position:
        x: -180
        "y": -70
      tempMetlId:
